version: 2

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: false
   builder: html

python:
  version: 3.9.10
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
